### ISSUE TITLE
Add support for docker-compose.yml if file is not specified in DockerComposeConfig

### ISSUE THREAD

**Issue by DmitrySandalov** [skanehira/docker-compose.vim#3]
`docker-compose.vim` fails with the following error when opening a `docker-compose.yml` (not `.yaml`) and running `:DockerComposeUp` without `:DockerComposeConfig`:
```
Error detected while processing function docker_compose#command#up[2]..docker_compose#utils#check#filereadable:                                    
line    2:                                                                                                                                         
E15: Invalid expression: . ' is not exist or readable')                                                                                            
E116: Invalid arguments for function docker_compose#utils#message#err                                                                              
```

From README.md
> If {file} is not specified, the plugin will find docker-compose.yaml from the current directory and use it.

From [Compose file version 3 reference](https://docs.docker.com/compose/compose-file/)
> Tip: You can use either a .yml or .yaml extension for this file. They both work.

`docker-compose.yml` files should be supported as well.

**Comment by skanehira** [comment]
Support `docker-compose.yml` in this commit 9022075 :)
